// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kojzroxicueotaioryip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvanpyb3hpY3Vlb3RhaW9yeWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MzYyMzEsImV4cCI6MjA3NTIxMjIzMX0.HDq8WUYGlOHBrYLOBFxYAneuIJ6BTDYuh6U4eeNuk0w"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});